# solving linear system equation

In [1]:
import numpy as np

A = np.array([[1,3,4],[6,4,1],[2,2,2]])
A

array([[1, 3, 4],
       [6, 4, 1],
       [2, 2, 2]])

In [2]:
B = np.array([5,16,11])
B

array([ 5, 16, 11])

In [3]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.75 , -0.25 ,  1.625],
       [ 1.25 ,  0.75 , -2.875],
       [-0.5  , -0.5  ,  1.75 ]])

In [4]:
np.dot(A_inv,B)

array([ 10.125, -13.375,   8.75 ])